package selenium.testcase;// Generated by Selenium IDE
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import selenium.page.App;

import java.util.Map;

public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  public static App app;

  @BeforeClass
  public static void beforeAll() {
    app = new App();
    app.loginWithCookie();
  }

  @AfterClass
  public static void afterAll() throws InterruptedException {
    app.quit();
  }
}
